### PR TITLE
Reorganize the grammar to follow C# code structure and fix couple of issues

### PR DESCRIPTION
**Pull request by ivanz**
Reorganized the grammar to follow C#'s code structure, which makes it easier to follow and reduces risk of clashing regex.

@damieng  I am going to hold off merging this until you give me a heads up that you are done with your port of changes from Atom (awesome stuff - thanks for that) to avoid you any pain pulling those over!

Feedback is also welcome of course :)

### CODE REVIEW

**Comment by damieng** [comment]
Just a heads up - the dashed name for keys makes things uglier in cson as it forces quoting :(

**Comment by ivanz** [comment]
Happy to change to underscore if that helps. Hopefully we can make the Atom and VSCode plugins pull this repo to avoid making changes in local repos and porting over every time? Thoughts?

**Comment by damieng** [comment]
Not sure of the logistics around automatically pulling from another repo.  Might want to also hold off on the refactoring until the VSCode people can sync up with changes as well.

**Comment by ivanz** [comment]
No worries about VSCode - I will create a PR there with the latest changes and I have no doubts it will be merged.

I would like to get this repo in a state where you can copy paste the output over what you have in the Atom repo. I had a quick look just now comparing the two outputs from master and there are only a handful differences left before that's the case and none of them blockers on the VSCode end afaict! 👍

**Pull request closed without merging**
